### PR TITLE
Add our own layout

### PR DESCRIPTION
**Pull request by pkgdemon**

### CODE REVIEW

**Review by dszidi — CHANGES_REQUESTED** [review]
Everything in the diff seems good to me. One request though. Could we perhaps setup some environment variables for layout? Of course if GNUstep has these variables already then let's use them wherever we cab. It might make future tweaks to this repo easier. I'm hoping it would reduce merge conflicts in the future as well. I will have to fix such conflicts on my wayland branch and thought this approach might avoid future pain

Maybe something like `DUBSTEP_LAYOUT_MAKEFILES=/Developer/Makefiles` ?

**Comment by dszidi** [comment]
deinstall doesn't work.

```
root@dubstep:~/ds-base # make deinstall
cd scripts && ./clean.sh
cd scripts && ./deinstall.sh
[: missing ]
```

**Comment by pkgdemon** [comment]
> `make clean` worked
> 
> `make deinstall` doesn't work. Output below
> 
> ```
> root@dubstep:~/ds-base # make deinstall
> cd scripts && ./clean.sh
> cd scripts && ./deinstall.sh
> [: missing ]
> ```

Ah thanks good catch.  I will fix here momentarily.

**Review by dszidi — APPROVED** [review]
Confirmed `makedeinstall` now works.
LGTM

**Pull request merged**
